name: Nuxt.js CI

on:
    push:
        branches: [main]

jobs:
    build-test:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: ["18.x", "20.x"] # Adjust based on Nuxt.js requirements
        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
            - name: Install dependencies
              run: npm ci
            - name: Run tests
              run: npm run test
            - name: Run playwright tests
              run: npm run test:play
            - name: Build for production
              run: npm run build
