name: Nuxt js CI

on:
  push:
    branches: [ main ] 

jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['18.x', '20.x']
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
      - run: npm ci
      - run: npm run test
      - run: npm run build
    
